---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sirp7472/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH/
    - cd $DEPLOYPATH
    - mkdir -p storage/framework/cache/data
    - mkdir -p storage/framework/sessions
    - mkdir -p storage/framework/views
    - mkdir -p storage/logs
    - mkdir -p bootstrap/cache
    - chmod -R 775 storage bootstrap/cache
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan optimize:clear
