name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main # Jalankan otomatisasi hanya saat push ke branch main

jobs:
  web-deploy:
    name: Deploy Core & Public
    runs-on: ubuntu-latest
    
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Sesuaikan dengan versi PHP di Rumahweb kamu

    - name: Install Dependencies
      run: composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader

    # Langkah ini untuk upload file core Laravel ke folder 'laravel-core'
    - name: Sync Core to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets::FTP_SERVER }}
        username: ${{ secrets::FTP_USERNAME }}
        password: ${{ secrets::FTP_PASSWORD }}
        local-dir: ./
        server-dir: ./laravel-core/ # Sesuaikan nama foldernya
        exclude: |
          */.git
          */.git/**
          */node_modules/*
          */public/* # Kita kecualikan folder public dulu

    # Langkah ini untuk upload isi folder public ke 'public_html'
    - name: Sync Public to public_html
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets::FTP_SERVER }}
        username: ${{ secrets::FTP_USERNAME }}
        password: ${{ secrets::FTP_PASSWORD }}
        local-dir: ./public/
        server-dir: ./public_html/